#!/usr/bin/env python3
"""Build single-file adapters from package-manifest.toml."""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_manifest(root: Path = ROOT) -> dict:
    with (root / "package-manifest.toml").open("rb") as handle:
        return tomllib.load(handle)


def slug(text: str) -> str:
    text = text.strip().casefold()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    return re.sub(r"[\s-]+", "-", text).strip("-")


def rewrite_local_links(text: str, root: Path) -> str:
    """Rewrite links to bundled Markdown documents into flat anchors."""
    pattern = re.compile(r"\[([^\]]+)\]\(((?:references|examples)/[^)#]+\.md)(#[^)]+)?\)")

    def replace(match: re.Match[str]) -> str:
        label, rel, fragment = match.group(1), match.group(2), match.group(3)
        target = root / rel
        if not target.is_file():
            return match.group(0)
        if fragment:
            return f"[{label}](#{fragment[1:]})"
        heading = next(
            (line[2:].strip() for line in target.read_text(encoding="utf-8").splitlines() if line.startswith("# ")),
            target.stem,
        )
        return f"[{label}](#{slug(heading)})"

    return pattern.sub(replace, text)


def profile_config(manifest: dict, profile: str) -> tuple[str, list[str]]:
    cfg = manifest["flat"][profile]
    output = cfg["output"]
    sources = cfg["sources"]
    if not isinstance(output, str) or not isinstance(sources, list) or not sources:
        raise ValueError(f"flat.{profile} must define output and non-empty sources")
    if sources[0] != "SKILL.md":
        raise ValueError(f"flat.{profile}.sources must begin with SKILL.md")
    return output, sources


def render(profile: str, root: Path = ROOT, manifest: dict | None = None) -> str:
    manifest = manifest or load_manifest(root)
    _, sources = profile_config(manifest, profile)

    chunks: list[str] = []
    for index, rel in enumerate(sources):
        path = root / rel
        if not path.is_file():
            raise FileNotFoundError(path)
        content = rewrite_local_links(path.read_text(encoding="utf-8"), root).rstrip()
        if index == 0:
            chunks.append(content)
            chunks.append(
                f"\n\n<!-- Generated {profile} flat adapter. Source order is defined in "
                "package-manifest.toml. Do not edit this file directly. -->"
            )
        else:
            chunks.append(f"\n\n---\n\n<!-- Source: {rel} -->\n\n{content}")
    return "".join(chunks) + "\n"


def process_profile(profile: str, *, check: bool, stdout: bool, manifest: dict) -> bool:
    output_rel, _ = profile_config(manifest, profile)
    output = ROOT / output_rel
    content = render(profile, ROOT, manifest)

    if stdout:
        if profile != "runtime":
            sys.stdout.write(f"\n<!-- PROFILE: {profile} -->\n")
        sys.stdout.write(content)
        return True

    if check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            print(f"stale generated adapter: {output_rel}", file=sys.stderr)
            return False
        print(f"adapter is current: {output_rel} ({len(content.encode('utf-8')):,} bytes)")
        return True

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"wrote {output_rel} ({len(content.encode('utf-8')):,} bytes)")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", choices=("runtime", "full", "all"), default="all")
    parser.add_argument("--check", action="store_true", help="fail if selected generated adapters are stale")
    parser.add_argument("--stdout", action="store_true", help="write selected generated content to stdout")
    args = parser.parse_args(argv)

    manifest = load_manifest(ROOT)
    profiles = ("runtime", "full") if args.profile == "all" else (args.profile,)
    ok = all(process_profile(p, check=args.check, stdout=args.stdout, manifest=manifest) for p in profiles)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
